#!/usr/bin/env python3
"""Install (or remove) agenttij's Zellij keybindings.

The bindings have to go *inside* an existing `keybinds` block, not in a second
one next to it. Zellij reads keybinds with `kdl_config.get("keybinds")`, which
returns only the first matching node — a second block parses cleanly, passes
`zellij setup --check`, and is then silently ignored. Its children, on the other
hand, are all iterated, so adding a `shared_except` block inside the first
`keybinds` node works.

usage: zellij-keybinds.py <install|uninstall> <config.kdl> <url> <summon> <cycle> <back> <focus>
"""

import re
import sys

BEGIN = "// agenttij:begin — regenerated by scripts/install.sh"
END = "// agenttij:end"


def block(url, summon, cycle, back, focus, indent):
    """Our `shared_except` block, indented to sit inside a `keybinds` node."""
    lines = [
        BEGIN,
        '// Summon a sidebar in any session, including one you jumped into.',
        'shared_except "locked" {',
        f'    bind "{summon}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        "            floating true",
        "            move_to_focused_tab true",
        "        }",
        "    }",
        "    // Cycle to the next pane in the row on screen — the editor beside the",
        "    // agent, and back. Global because the point is doing it while the agent",
        "    // has focus. Zellij identifies a plugin by url *and* configuration, so",
        "    // this repeats agenttij-workspace.kdl's configuration: change one,",
        "    // change both, or it will launch a second sidebar instead.",
        f'    bind "{cycle}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "cycle"',
        "            launch_new false",
        '            scope "session"',
        '            solo "true"',
        "        }",
        "    }",
        "    // Focus the sidebar wherever you are. Matching configuration means",
        "    // this finds the docked sidebar rather than launching another one.",
        f'    bind "{focus}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        "            floating false",
        "            move_to_focused_tab true",
        '            scope "session"',
        '            solo "true"',
        "        }",
        "    }",
        "    // Back to the session you came from.",
        f'    bind "{back}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "back"',
        "            launch_new false",
        '            scope "session"',
        '            solo "true"',
        "        }",
        "    }",
        "}",
        END,
    ]
    return "".join(f"{indent}{line}\n" for line in lines)


def strip_existing(text):
    """Removes any block we have written before, whatever the marker's wording.

    Earlier versions appended a whole `keybinds` block of their own; the marker
    range covers it, so stripping cleans that up too.
    """
    # Note the absence of a leading \n: consuming the newline before the marker
    # would swallow the one that terminates the enclosing `keybinds {` line,
    # merging it with whatever follows and breaking the next insertion.
    pattern = re.compile(
        r"^[ \t]*// agenttij:begin.*?^[ \t]*// agenttij:end[ \t]*\n",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text)


def insert(text, url, summon, cycle, back, focus):
    lines = text.splitlines(keepends=True)

    for index, line in enumerate(lines):
        stripped = line.strip()
        if re.fullmatch(r"keybinds\s*\{", stripped):
            # Match the indentation the block's own children use.
            indent = " " * 4
            for following in lines[index + 1 :]:
                if following.strip():
                    indent = following[: len(following) - len(following.lstrip())]
                    break
            lines.insert(index + 1, block(url, summon, cycle, back, focus, indent))
            return "".join(lines)

    # No keybinds block at all: contribute a whole one.
    tail = "" if text.endswith("\n") or not text else "\n"
    return text + tail + "\nkeybinds {\n" + block(url, summon, cycle, back, focus, " " * 4) + "}\n"


def main(argv):
    if len(argv) != 8 or argv[1] not in ("install", "uninstall"):
        sys.exit(__doc__)

    mode, path, url, summon, cycle, back, focus = argv[1:]

    try:
        with open(path) as handle:
            text = handle.read()
    except FileNotFoundError:
        text = ""

    text = strip_existing(text)
    if mode == "install":
        text = insert(text, url, summon, cycle, back, focus)

    with open(path, "w") as handle:
        handle.write(text)


if __name__ == "__main__":
    main(sys.argv)
