#!/usr/bin/env python3
"""Install (or remove) agenttij's Zellij keybindings.

The bindings have to go *inside* an existing `keybinds` block, not in a second
one next to it. Zellij reads keybinds with `kdl_config.get("keybinds")`, which
returns only the first matching node — a second block parses cleanly, passes
`zellij setup --check`, and is then silently ignored. Its children, on the other
hand, are all iterated, so adding a `shared_except` block inside the first
`keybinds` node works.

The last argument is the layout's `group` template, or empty — install.sh reads it
out of the layouts rather than asking anyone to type it twice. It has to be
repeated here because a plugin's identity is its url *plus* its configuration: a
sidebar started from a layout that carries `group` is a different instance from
the one these bindings would talk to, so without it every one of them launches a
second sidebar instead of reaching the docked one. Measured, with the pane list
to prove it.

usage: zellij-keybinds.py <install|uninstall> <config.kdl> <url> <summon> <cycle> <back> <focus> <new> <add> <jump> <group>
"""

import re
import sys

BEGIN = "// agenttij:begin — regenerated by scripts/install.sh"
END = "// agenttij:end"


def block(url, summon, cycle, back, focus, new, add, jump, group, indent):
    """Our `shared_except` block, indented to sit inside a `keybinds` node."""
    # Going back through a row, and flipping between two of its panes, live
    # beside the cycle key rather than getting keys of their own: whatever
    # modifier you cycle with, these are it with Shift and with a quote.
    modifier, key = cycle.rsplit(" ", 1)
    cycle_back = f"{modifier} {key.upper()}"
    flip = f"{modifier} '"
    # A new row somewhere you choose is the new-row key with Shift.
    new_modifier, new_key = new.rsplit(" ", 1)
    pick = f"{new_modifier} {new_key.upper()}"
    # What every binding that has to *find* the docked sidebar must repeat,
    # exactly as the layout writes it.
    matched = ['            scope "session"', '            solo "true"']
    if group:
        matched.append(f'            group "{group}"')

    lines = [
        BEGIN,
        "// Everywhere you could go, filtered by typing. Its configuration has to",
        "// match what the sidebar's `/` opens, or this launches a second palette",
        "// instead of focusing the one already there — `solo` included, which is",
        "// what the palette needs to know to park rather than split when it",
        "// attaches to a machine somewhere else.",
        f'shared_except "locked" {{',
        f'    bind "{jump}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        '            jump "true"',
        '            pane_title "jump"',
        '            solo "true"',
        "            floating true",
        "            move_to_focused_tab true",
        "        }",
        "    }",
        "}",
        "// A new row in a directory you pick: zoxide's list and everywhere this",
        "// machine is already working, filtered by typing. It carries no `group`",
        "// and no `scope`: the picker only chooses, and the sidebar does the",
        "// opening, so this configuration is the whole of its identity.",
        f'shared_except "locked" {{',
        f'    bind "{pick}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        '            dirs "true"',
        '            pane_title "open in"',
        "            floating true",
        "            move_to_focused_tab true",
        "        }",
        "    }",
        "}",
        '// Summon a sidebar in any session, including one you jumped into.',
        'shared_except "locked" {',
        f'    bind "{summon}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        "            floating true",
        "            move_to_focused_tab true",
        "        }",
        "    }",
        "    // Cycle to the next pane in the row on screen — the editor beside the",
        "    // agent, and back. Global because the point is doing it while the agent",
        "    // has focus. Zellij identifies a plugin by url *and* configuration, so",
        "    // this repeats agenttij-workspace.kdl's configuration: change one,",
        "    // change both, or it will launch a second sidebar instead. That",
        "    // includes `group`, which install.sh copies out of the layouts.",
        f'    bind "{cycle}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "cycle"',
        "            launch_new false",
        *matched,
        "        }",
        "    }",
        "    // Focus the sidebar wherever you are. Matching configuration means",
        "    // this finds the docked sidebar rather than launching another one.",
        f'    bind "{focus}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        "            floating false",
        "            move_to_focused_tab true",
        *matched,
        "        }",
        "    }",
        "    // A new row (a new agent), and a pane added to the row on screen.",
        "    // Both work with an agent focused, which is when you want them.",
        f'    bind "{new}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "new"',
        "            launch_new false",
        *matched,
        "        }",
        "    }",
        f'    bind "{add}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "add"',
        "            launch_new false",
        *matched,
        "        }",
        "    }",
        "    // Around the row on screen without going to the sidebar: back a",
        "    // pane, flip to the one before, or straight to a numbered one — the",
        "    // number each pane frame already shows as `2/5`.",
        f'    bind "{cycle_back}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "cycle-back"',
        "            launch_new false",
        *matched,
        "        }",
        "    }",
        f'    bind "{flip}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "flip"',
        "            launch_new false",
        *matched,
        "        }",
        "    }",
        *[
            line
            for index in range(1, 10)
            for line in (
                f'    bind "Alt {index}" {{',
                f'        MessagePlugin "{url}" {{',
                '            name "pane"',
                f'            payload "{index}"',
                "            launch_new false",
                *matched,
                "        }",
                "    }",
            )
        ],
        "    // Back to the row you were on before this one.",
        f'    bind "{back}" {{',
        f'        MessagePlugin "{url}" {{',
        '            name "back"',
        "            launch_new false",
        *matched,
        "        }",
        "    }",
        "}",
        END,
    ]
    return "".join(f"{indent}{line}\n" for line in lines)


def strip_existing(text):
    """Removes any block we have written before, whatever the marker's wording.

    Earlier versions appended a whole `keybinds` block of their own; the marker
    range covers it, so stripping cleans that up too.
    """
    # Note the absence of a leading \n: consuming the newline before the marker
    # would swallow the one that terminates the enclosing `keybinds {` line,
    # merging it with whatever follows and breaking the next insertion.
    pattern = re.compile(
        r"^[ \t]*// agenttij:begin.*?^[ \t]*// agenttij:end[ \t]*\n",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text)


def insert(text, url, summon, cycle, back, focus, new, add, jump, group):
    lines = text.splitlines(keepends=True)

    for index, line in enumerate(lines):
        stripped = line.strip()
        if re.fullmatch(r"keybinds\s*\{", stripped):
            # Match the indentation the block's own children use.
            indent = " " * 4
            for following in lines[index + 1 :]:
                if following.strip():
                    indent = following[: len(following) - len(following.lstrip())]
                    break
            lines.insert(
                index + 1,
                block(url, summon, cycle, back, focus, new, add, jump, group, indent),
            )
            return "".join(lines)

    # No keybinds block at all: contribute a whole one.
    tail = "" if text.endswith("\n") or not text else "\n"
    return (
        text
        + tail
        + "\nkeybinds {\n"
        + block(url, summon, cycle, back, focus, new, add, jump, group, " " * 4)
        + "}\n"
    )


def main(argv):
    if len(argv) != 12 or argv[1] not in ("install", "uninstall"):
        sys.exit(__doc__)

    mode, path, url, summon, cycle, back, focus, new, add, jump, group = argv[1:]

    try:
        with open(path) as handle:
            text = handle.read()
    except FileNotFoundError:
        text = ""

    text = strip_existing(text)
    if mode == "install":
        text = insert(text, url, summon, cycle, back, focus, new, add, jump, group)

    with open(path, "w") as handle:
        handle.write(text)


if __name__ == "__main__":
    main(sys.argv)
