#!/usr/bin/env python3
"""Install (or remove) agenttij's Zellij keybindings.

The bindings have to go *inside* an existing `keybinds` block, not in a second
one next to it. Zellij reads keybinds with `kdl_config.get("keybinds")`, which
returns only the first matching node — a second block parses cleanly, passes
`zellij setup --check`, and is then silently ignored. Its children, on the other
hand, are all iterated, so adding a `shared_except` block inside the first
`keybinds` node works.

usage: zellij-keybinds.py <install|uninstall> <config.kdl> <url> <summon>
"""

import re
import sys

BEGIN = "// agenttij:begin — regenerated by scripts/install.sh"
END = "// agenttij:end"


def block(url, summon, indent):
    """Our `shared_except` block, indented to sit inside a `keybinds` node."""
    lines = [
        BEGIN,
        '// Summon a sidebar in any session, including one you jumped into.',
        'shared_except "locked" {',
        f'    bind "{summon}" {{',
        f'        LaunchOrFocusPlugin "{url}" {{',
        "            floating true",
        "            move_to_focused_tab true",
        "        }",
        "    }",
        "}",
        END,
    ]
    return "".join(f"{indent}{line}\n" for line in lines)


def strip_existing(text):
    """Removes any block we have written before, whatever the marker's wording.

    Earlier versions appended a whole `keybinds` block of their own; the marker
    range covers it, so stripping cleans that up too.
    """
    # Note the absence of a leading \n: consuming the newline before the marker
    # would swallow the one that terminates the enclosing `keybinds {` line,
    # merging it with whatever follows and breaking the next insertion.
    pattern = re.compile(
        r"^[ \t]*// agenttij:begin.*?^[ \t]*// agenttij:end[ \t]*\n",
        re.MULTILINE | re.DOTALL,
    )
    return pattern.sub("", text)


def insert(text, url, summon):
    lines = text.splitlines(keepends=True)

    for index, line in enumerate(lines):
        stripped = line.strip()
        if re.fullmatch(r"keybinds\s*\{", stripped):
            # Match the indentation the block's own children use.
            indent = " " * 4
            for following in lines[index + 1 :]:
                if following.strip():
                    indent = following[: len(following) - len(following.lstrip())]
                    break
            lines.insert(index + 1, block(url, summon, indent))
            return "".join(lines)

    # No keybinds block at all: contribute a whole one.
    tail = "" if text.endswith("\n") or not text else "\n"
    return text + tail + "\nkeybinds {\n" + block(url, summon, " " * 4) + "}\n"


def main(argv):
    if len(argv) != 5 or argv[1] not in ("install", "uninstall"):
        sys.exit(__doc__)

    mode, path, url, summon = argv[1:]

    try:
        with open(path) as handle:
            text = handle.read()
    except FileNotFoundError:
        text = ""

    text = strip_existing(text)
    if mode == "install":
        text = insert(text, url, summon)

    with open(path, "w") as handle:
        handle.write(text)


if __name__ == "__main__":
    main(sys.argv)
